### ISSUE TITLE
[BUG]: shipped with broken arch keys

### ISSUE THREAD

**Issue by mandoof1** [Athena-OS/athena-iso#62] opened 2023-07-24 23:41 UTC
### Athena OS version

polias

### Which environment or technology are you using?

- [X] Baremetal
- [ ] VirtualBox Virtual Machine
- [ ] VMware Virtual Machine
- [ ] Hyper-V Virtual Machine
- [ ] QEMU/KVM
- [ ] Parallels
- [ ] UTM
- [ ] Container
- [ ] WSL

### Repro steps

if you try to manuallly update your distro atleast for me i got a broken arch keys

### Expected behavior

its supposed to update it doesnt

### Actual behavior

to solve it run these commands your welcome
Sudo pacman -S archlinux-keyring
Sudo pacman-key --init
Sudo pacman-key --populate
Sudo pacman-key --refresh-keys
Sudo pacman -Sy archlinux-keyring

**Comment by D3vil0p3r** [comment] 2023-07-28 19:43
It is not a bug related specifically to Athena. It is related to keys used on mirrors of Arch. They can be autofixed over time when key providers fix them, or, in some cases, running the commands you used there. Closing.

**Closed by D3vil0p3r** 2023-07-28 19:43 UTC
Labels: bug
